name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release --locked

      - name: Deploy - Create and Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/release/yuki_monitor
          artifactName: yuki_monitor
          generateReleaseNotes: true
