name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release --locked

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: yuki_monitor
          path: target/release/yuki_monitor

      - name: Create and Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/release/yuki_monitor
          artifactName: yuki_monitor
          generateReleaseNotes: true
